version: '3.9'

services:
  active-tasks-map:
    image: node:20-alpine
    container_name: active-tasks-map
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "9898:5173"   # внешний 9898 -> внутренний 5173 (порт Vite)
    command: sh -c "npm install && npm run dev -- --host"