version: '3.9'

services:
  active-tasks-map:
    build: .
    container_name: active-tasks-map
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "9898:5173"
    command: sh -c "npm install && npm run dev -- --host"
